from modules.idea_generator import generate_idea
from modules.script_writer import write_script
from modules.voice_generator import generate_voice
from modules.video_builder import build_video
from modules.thumbnail_maker import make_thumbnail
from modules.uploader import upload_to_youtube
import datetime

def run_pipeline():
    print("\n========== AI MEDIA PIPELINE ==========")
    print(f"Started: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}\n")

    # Step 1: Generate Idea
    print("[1/6] Generating video idea...")
    title, topic = generate_idea()
    print(f"      Title : {title}")
    print(f"      Topic : {topic}\n")

    # Step 2: Write Script
    print("[2/6] Writing script with Groq...")
    script = write_script(title, topic)
    print(f"      Script length: {len(script.split())} words\n")

    # Step 3: Generate Voice
    print("[3/6] Generating AI voice (Edge-TTS)...")
    audio_path = generate_voice(script, title)

    # Step 4: Build Video
    print("[4/6] Building video with MoviePy...")
    video_path = build_video(audio_path, script, title)

    # Step 5: Make Thumbnail
    print("[5/6] Creating thumbnail...")
    thumbnail_path = make_thumbnail(title)

    # Step 6: Upload to YouTube
    # Step 6: Upload to YouTube
    print("[6/6] Uploading to YouTube...")

    # Clean title for YouTube (max 100 chars, no special chars)
    import re
    yt_title = re.sub(r'[^\w\s\-\:\!\?\,\.\(\)]', '', title).strip()
    yt_title = (yt_title[:91] + " #Shorts") if yt_title else "AI Video #Shorts"

    description = f"{topic}\n\nGenerated by AI Media Pipeline.\n\n#Shorts #AI #Technology"
    tags = ["Shorts", "AI", "Technology", "Automation", "Short"]
    video_id = upload_to_youtube(video_path, thumbnail_path, yt_title, description, tags)

    print("\n========== DONE ==========")
    print(f"Video live: https://youtu.be/{video_id}")

if __name__ == "__main__":
    run_pipeline()